version: "3"
services:
  golang:
    container_name: golang
    build:
      context: ./
    volumes:
      - ./app:/go/src/app
    tty: true

  mariadb:
    container_name: mariadb
    image: mariadb:10.5.4
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
